### PR TITLE
Ensure JVerify is robust to class with no constructors

### LINKED ISSUE #45: Crash when a class does not define any constructor
Launching JVerify on the following class raises an exception:

```
public class A {
  public int f;
}
```

Exception trace is:
```
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 5
        at jdk.compiler/com.sun.tools.javac.util.Position$LineTabMapImpl.getColumnNumber(Position.java:266)
        at com.aws.jverify.verifier.JavaToDafnyCompiler.toToken(JavaToDafnyCompiler.java:697)
        at com.aws.jverify.verifier.JavaToDafnyCompiler.getName(JavaToDafnyCompiler.java:571)
        at com.aws.jverify.verifier.JavaToDafnyCompiler.translateMethodDecl(JavaToDafnyCompiler.java:188)
        at com.aws.jverify.verifier.JavaToDafnyCompiler.translateMember(JavaToDafnyCompiler.java:160)
        at com.aws.jverify.verifier.JavaToDafnyCompiler.translateClass(JavaToDafnyCompiler.java:118)
        at com.aws.jverify.verifier.JavaToDafnyCompiler.translateTypeDeclaration(JavaToDafnyCompiler.java:94)
        at com.aws.jverify.verifier.JavaToDafnyCompiler.analyzeJavaCode(JavaToDafnyCompiler.java:75)
        at com.aws.jverify.verifier.Driver.verifyJavaFiles(Driver.java:32)
public class A {
        at com.aws.jverify.verifier.Driver.verifyJavaPaths(Driver.java:27)
        at com.aws.jverify.verifier.AppCommand.call(Main.java:56)
        at com.aws.jverify.verifier.AppCommand.call(Main.java:25)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at com.aws.jverify.verifier.Main.main(Main.java:20)

```

Adding a constructor to A makes verification pass.

### PR DESCRIPTION
**Pull request by olivier-aws**
### What was changed?
- If a node does not originate from source, use the nearest surrounding origin instead. For example, a default constructor will get the origin of its containing class.
- Fix bug in testing code to enable test files with public classes
- Remove some code duplication in JavaToDafnyCompiler.java

### How has this been tested?
- Added a test case in TestVerifier.java

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache-2.0](https://github.com/aws/jverify?tab=Apache-2.0-1-ov-file#readme).</small>

### CODE REVIEW

**Comment by olivier-aws** [comment]
Not sure this is the best solution. It unblocks the situation but I'm not sure of the impact of returning a Token(-1,-1). Should we return the Token for the class definition instead?

**Review by keyboardDrummer — APPROVED** [review]
Made a few changes. Please review them before merging.

File: verifier/src/main/java/com/aws/jverify/verifier/Driver.java [hunk 1]
```diff
@@ -10,9 +10,9 @@
 
 public class Driver {
 
-    public static int verifyJavaExample(VerifierOptions options, String javaCode, Writer output) throws IOException {
+    public static int verifyJavaExample(VerifierOptions options, Path javaFile, Writer output) throws IOException {
         var files = new ArrayList<JavaFileObject>();
-        files.add(new SourceFile("test.java", javaCode));
+        files.add(new SourceFile(javaFile, Files.readString(javaFile)));
```
Comment (olivier-aws) [inline verifier/src/main/java/com/aws/jverify/verifier/Driver.java:15]: I think this is the root cause for these check failures:

```
 org.opentest4j.AssertionFailedError: expected: </test.java(7:9-7:21): Error: assertion might not hold

    Dafny program verifier finished with 2 verified, 1 error
    > but was: <src/test/java/com/aws/jverify/AssertFalse.java(7:9-7:21): Error: assertion might not hold

    Dafny program verifier finished with 2 verified, 1 error
    >
```

Should we revert that temporarily while we find a better solution for our CI tests?

Comment (keyboardDrummer) [reply verifier/src/main/java/com/aws/jverify/verifier/Driver.java:15]: Made a fix
