### PR TITLE
Fix array copy

### LINKED ISSUE #333: Crash when copying an array cell into another array cell
Analyze this code with JVerify:
```java
    static void arrayCopy() {
        int[] tab = new int[4];
        int[] tab2 = new int[4];
        tab2[1] = 10;
        tab[1] = tab2[1];
        check(tab[1]==10);
    }
```
There is a crash
```
java.lang.RuntimeException: not supported. should have already been lowered
	at com.aws.jverify.verifier.compiler.dafnygenerator.base.ExpressionCompiler.translateArrayAccess(ExpressionCompiler.java:374)
...
```

### PR DESCRIPTION
**Pull request by olivier-aws**
### What was changed?
Fix for issue #333 

### How has this been tested?
Added a test case

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache-2.0](https://github.com/aws/jverify?tab=Apache-2.0-1-ov-file#readme).</small>

### CODE REVIEW

File: verifier/src/main/java/com/aws/jverify/verifier/compiler/simplifications/ArrayCompiler.java [hunk 1]
```diff
@@ -65,12 +65,16 @@ public void visitNewClass(JCTree.JCNewClass tree) {
     public void visitAssign(JCTree.JCAssign tree) {
         if (tree.lhs instanceof JCTree.JCArrayAccess arrayAccess) {
             maker.pos = tree.pos;
-            result = maker.App(maker.Select(arrayAccess.getExpression(), setMethodSymbol), 
-                    List.of(arrayAccess.getIndex(), tree.getExpression()));
+            tree.rhs = super.translate(tree.rhs);
```
Comment (keyboardDrummer) [inline verifier/src/main/java/com/aws/jverify/verifier/compiler/simplifications/ArrayCompiler.java]: Should it be `super.translate` or `translate` ? Also, should we call `super.visitAssign(tree)` at the top instead of having this?

Comment (olivier-aws) [reply verifier/src/main/java/com/aws/jverify/verifier/compiler/simplifications/ArrayCompiler.java]: We can't call super.visitAssign(tree) at the top. This would translate
```java
  tab1[i] = tab2[i];
```
into
```dafny
  tab1.get(i) := tab2.get(i);
```
I think it is the same to call `translate` or `super.translate` because `ArrayCompiler` does not override the `translate` method anyway, but you are right that it seems more natural to call `translate`. Updated.

**Review by keyboardDrummer — APPROVED** [review]

**Comment by keyboardDrummer** [comment]
Nice, thanks :)
